Handle names with spaces

diff --git a/torywatch b/torywatch
--- a/torywatch
+++ b/torywatch
@@ -13,11 +13,8 @@ then
 	error "Please symlink $FOLDER to the watched folder"
 fi
 
-for i in $@
-do
-	msg=$(cp "$i" "$FOLDER" 2>&1)
-	if [[ $? -ne 0 ]]
-	then
-		error "Error copying torrent:\n$msg"
-	fi
-done
+msg=$(cp "$@" "$FOLDER" 2>&1)
+if [[ $? -ne 0 ]]
+then
+	error "Error copying torrent:\n$msg"
+fi
